# Generated by Django 5.2.5 on 2025-08-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
